/* tslint:disable */
import { AppError as SampleCubeRfqModelsAppError } from '../../SampleCube/RFQ.Models/app-error';
import { ItemLists as SampleCubeRfqModelsPurchaseOrderItemLists } from '../../SampleCube/RFQ.Models.PurchaseOrder/item-lists';
import { SupplierDetails as SampleCubeRfqModelsPurchaseOrderSupplierDetails } from '../../SampleCube/RFQ.Models.PurchaseOrder/supplier-details';
export interface PurchaseOrderDetailResponse {
  adminStatus?: null | number;
  appError?: SampleCubeRfqModelsAppError;
  baseUrl?: null | string;
  billingAddress?: null | string;
  companyId?: number;
  contactPerson?: null | string;
  createdBy?: number;
  createdDate?: string;
  currencyId?: number;
  currencyName?: null | string;
  email?: null | string;
  expiryDate?: string;
  isActive?: boolean;
  isRevised?: boolean;
  itemLists?: null | Array<SampleCubeRfqModelsPurchaseOrderItemLists>;
  legalEntityName?: null | string;
  locationId?: number;
  locationName?: null | string;
  managerApprover?: null | string;
  name?: null | string;
  paymentTerms?: number;
  paymentTermsName?: null | string;
  poAmount?: number;
  poApprover?: null | string;
  poApproverEmail?: null | string;
  poCreatorEmail?: null | string;
  poCreatorName?: null | string;
  poNumber?: null | string;
  purchaseOrderGuid?: string;
  purchaseOrderId?: number;
  remarks?: null | string;
  shippingAddress?: null | string;
  shortName?: null | string;
  statusId?: number;
  success?: boolean;
  supplierDetails?: SampleCubeRfqModelsPurchaseOrderSupplierDetails;
  supplierId?: number;
  traceIdentifier?: null | string;
  updatedBy?: number;
  updatedDate?: string;
}
