/* tslint:disable */
import { AppError as SampleCubeRfqModelsAppError } from '../../SampleCube/RFQ.Models/app-error';
export interface RfqRequestOverviewResponse {
  accountId?: number;
  appError?: SampleCubeRfqModelsAppError;
  bidId?: number;
  billingEntityID?: number;
  billingEntityName?: null | string;
  chartStudies?: boolean;
  clientBidNumber?: null | string;
  clientContact?: null | string;
  clientDiscount?: number;
  clientDiscoutApplied?: number;
  clientId?: number;
  clientOwnerCategoryId?: number;
  clientProgram?: null | string;
  clientProgramId?: number;
  client_Project_Number?: null | string;
  contactPerson?: null | string;
  createdBy?: number;
  createdDate?: string;
  currencyId?: number;
  currencyMultiplier?: number;
  currencySymbol?: null | string;
  currencyType?: null | string;
  email?: null | string;
  endClientDiscount?: number;
  endClientDiscountApplied?: number;
  endClientProgram?: null | string;
  endClientProgramId?: number;
  end_Client?: null | string;
  end_ClientId?: number;
  end_Client_Project_Number?: null | string;
  industryId?: number;
  industryName?: null | string;
  isActive?: boolean;
  isInternal?: boolean;
  jobLocationId?: number;
  listStudiesId?: number;
  listStudiesName?: null | string;
  locationID?: number;
  locationName?: null | string;
  margin?: number;
  notification_Count?: number;
  phoneNo?: null | string;
  proposedBy?: null | string;
  rfqDesc?: null | string;
  rfqEndDate?: string;
  rfqId?: number;
  rfqName?: null | string;
  rfqProposalDesc?: null | string;
  rfqRequestGUID?: string;
  rfqStartDate?: string;
  rfqStatusId?: number;
  rfqTermConditions?: null | string;
  success?: boolean;
  supplierCurrencyId?: number;
  supplierCurrencySymbol?: null | string;
  supplierCurrencyType?: null | string;
  targetAudience?: null | string;
  traceIdentifier?: null | string;
  updatedBy?: number;
  updatedDate?: string;
}
