/* tslint:disable */
export interface UpdateRfqOverviewRequest {
  accountId?: number;
  bidId?: number;
  bidManager?: null | string;
  chartStudies?: boolean;
  clientBidNumber?: null | string;
  clientDiscount?: number;
  clientDiscoutApplied?: number;
  clientId?: number;
  clientOwnerCategoryId?: number;
  clientProgramId?: number;
  client_Project_Number?: null | string;
  closeDate?: string;
  createdBy?: number;
  createdDate?: string;
  currencyId?: number;
  currencyMultiplier?: number;
  description?: null | string;
  endClientDiscount?: number;
  endClientDiscountApplied?: number;
  endClientProgramId?: number;
  end_Client?: null | string;
  end_ClientId?: number;
  end_Client_Project_Number?: null | string;
  industryId?: number;
  isActive?: boolean;
  isInternal?: boolean;
  isMarginUpdate?: boolean;
  jobLocationId?: number;
  listStudiesId?: number;
  margin?: number;
  name?: null | string;
  rfqId?: number;
  rfqProposalDesc?: null | string;
  rfqRequestGUID?: string;
  rfqTermConditions?: null | string;
  startDate?: string;
  startEndDate?: string;
  statusId?: number;
  strCloseDate?: null | string;
  strStartDate?: null | string;
  subjectName?: null | string;
  supplierCurrencyId?: number;
  targetAudience?: null | string;
  updatedBy?: number;
}
