/* tslint:disable */
import { AppError as SampleCubeRfqModelsAppError } from '../../SampleCube/RFQ.Models/app-error';
import { InvoiceAttachments as SampleCubeRfqModelsInvoiceInvoiceAttachments } from '../../SampleCube/RFQ.Models.Invoice/invoice-attachments';
import { InvoiceItem as SampleCubeRfqModelsInvoiceInvoiceItem } from '../../SampleCube/RFQ.Models.Invoice/invoice-item';
export interface InvoiceDetailResponse {
  appError?: SampleCubeRfqModelsAppError;
  attachment?: null | string;
  categoryId?: number;
  companyId?: number;
  companyName?: null | string;
  createdBy?: number;
  creditNoteAmount?: number;
  currency?: null | string;
  currencyId?: number;
  frequency?: null | string;
  invoiceAmount?: number;
  invoiceAttachments?: null | Array<SampleCubeRfqModelsInvoiceInvoiceAttachments>;
  invoiceDate?: string;
  invoiceId?: number;
  invoiceItems?: null | Array<SampleCubeRfqModelsInvoiceInvoiceItem>;
  invoiceNumber?: null | string;
  isActive?: boolean;
  location?: null | string;
  locationId?: number;
  month?: number;
  pandHOptionsId?: null | number;
  paymentTerm?: number;
  paymentTermName?: null | string;
  poNumber?: null | string;
  projectId?: null | number;
  purchaseOrderId?: null | number;
  remark?: null | string;
  serviceMonth?: null | string;
  serviceType?: null | string;
  statusId?: number;
  success?: boolean;
  supplierId?: number;
  supplierInvoiceGUID?: string;
  traceIdentifier?: null | string;
  updatedBy?: number;
  year?: number;
}
