/* tslint:disable */
import { AppError as SampleCubeRfqModelsAppError } from '../../SampleCube/RFQ.Models/app-error';
import { CreditNoteAttachments as SampleCubeRfqModelsCreditNotesCreditNoteAttachments } from '../../SampleCube/RFQ.Models.CreditNotes/credit-note-attachments';
import { CreditNoteItems as SampleCubeRfqModelsCreditNotesCreditNoteItems } from '../../SampleCube/RFQ.Models.CreditNotes/credit-note-items';
export interface CreditNoteDetailsResponse {
  accountId?: null | number;
  amount?: number;
  appError?: SampleCubeRfqModelsAppError;
  categoryId?: number;
  createdBy?: null | number;
  createdOn?: string;
  creditNoteAttachments?: null | Array<SampleCubeRfqModelsCreditNotesCreditNoteAttachments>;
  creditNoteDate?: string;
  creditNoteGUID?: string;
  creditNoteId?: number;
  creditNoteNumber?: null | string;
  currency?: null | string;
  currencyId?: number;
  frequency?: null | string;
  inv_CreditNoteItems?: null | Array<SampleCubeRfqModelsCreditNotesCreditNoteItems>;
  invoiceId?: number;
  invoiceNumber?: null | string;
  isActive?: null | boolean;
  isNetSuiteUpdated?: boolean;
  month?: number;
  paymentTerm?: number;
  paymentTermName?: null | string;
  poNumber?: null | string;
  projectId?: null | number;
  purchaseOrderId?: null | number;
  remarks?: null | string;
  serviceMonth?: null | string;
  serviceType?: null | string;
  statusId?: number;
  success?: boolean;
  supplierId?: number;
  tax?: number;
  traceIdentifier?: null | string;
  updatedBy?: null | number;
  updatedOn?: null | string;
  year?: number;
}
